name: 'artifactbundle-builder'
description: 'generate artifactbundle binaries'
inputs:
  depth:
    description: 'find executable targets'
    default: '0'
  path:
    description: 'custom working directory'
    default: '.'
  build-options:
    description: 'custom build options'
    default: ''
  configuration:
    description: 'swift build configuration'
    default: 'release'
  macos-archs:
    description: 'archs list. e.g.) x86_64 arm64'
    default: 'x86_64 arm64'

runs:
  using: 'composite'
  steps:
    - name: Get swift version
      id: get-version
      shell: bash
      run: |
        input=$(swift --version)

        regex="Swift version ([0-9]+\.[0-9]+(\.[0-9]+)?)"
        if [[ $input =~ $regex ]]; then
          version="${BASH_REMATCH[1]}"
          echo "version=$version" >> "$GITHUB_OUTPUT"
        else
          echo "missing swift version."
          exit 1
        fi
    - uses: actions/cache@v3
      with:
        path: .build
        key: swiftpm-${{ runner.os }}-${{ steps.get-version.outputs.version }}-${{ hashFiles(format('{0}/Package.swift', inputs.path)) }}
        restore-keys: |
          swiftpm-${{ runner.os }}-${{ steps.get-version.outputs.version }}-
          swiftpm-${{ runner.os }}-
    - name: Build bin
      id: build
      shell: bash
      run: |
        cd ${{ inputs.path }}

        BUILD_OPTS="${{ inputs.build-options }} -c ${{ inputs.configuration }}"
        if [ "${{ runner.os }}" = "macOS" ]; then
          ARCHS=$(echo "${{ inputs.macos-archs }}" | jq -Rnc 'inputs | split(" ") | map("--arch " + .)' | jq -rc 'join(" ")')
          BUILD_OPTS="$BUILD_OPTS $ARCHS"
        fi

        echo "builddir=$(swift build $BUILD_OPTS --show-bin-path)" >> "$GITHUB_OUTPUT"

        ROOT_PRODUCTS=$(swift package dump-package | jq -r '.products[] | select(.type | has("executable")) | .name')
        for PRODUCT in $ROOT_PRODUCTS; do
          swift build $BUILD_OPTS --product $PRODUCT
        done

        # currently limitation depth == 1
        if [ "${{ inputs.depth }}" != "0" ]; then
          NAMES=$(swift package show-dependencies --format json | jq -r '.dependencies[].name')
          for NAME in $NAMES; do
            DIR=.build/checkouts/$NAME
            PRODUCTS=$(swift package --package-path $DIR dump-package | jq -r '.products[] | select(.type | has("executable")) | .name')
            for PRODUCT in $PRODUCTS; do
              swift build $BUILD_OPTS --product $PRODUCT
            done
          done
        fi
    - name: Collect bins
      shell: bash
      run: |
        cd ${{ inputs.path }}

        _TRIPLE=$(swift -print-target-info | jq -r '.target.moduleTriple')
        if [ "${{ runner.os }}" = "macOS" ]; then
          TRIPLES=$(echo "${{ inputs.macos-archs }}" | jq -Rnc 'inputs | split(" ") | map(. + "-apple-macosx")')
          BUNDLE_EXT="bundle"
        else
          TRIPLES="[ \"$_TRIPLE\" ]"
          BUNDLE_EXT="resources"
        fi

        BUILD_DIR="${{ steps.build.outputs.builddir }}"
        OUTPUT_PATH=output/${{ steps.get-version.outputs.version }}/$_TRIPLE

        mkdir -p $OUTPUT_PATH/bin

        # copy executable
        find $BUILD_DIR -maxdepth 1 -type f -exec test -x {} \; -print | xargs -I '{}' mv {} $OUTPUT_PATH/bin

        for BIN in `ls $OUTPUT_PATH/bin`; do
          JSON=$(cat << EOS
        {
          "path": "$_TRIPLE/bin/$BIN",
          "supportedTriples": $TRIPLES
        }
        EOS
        )
          echo $JSON > $OUTPUT_PATH/$BIN.json
        done

        # add bundle
        find $BUILD_DIR -maxdepth 1 -name "*.$BUNDLE_EXT" -print | xargs -I '{}' mv {} $OUTPUT_PATH/bin

        # exclude test bundles
        rm -rf $OUTPUT_PATH/bin/*Tests.$BUNDLE_EXT

        # archive
        tar -cvzf output.tar.gz $OUTPUT_PATH
    - uses: actions/upload-artifact@v3
      with:
        name: artifact-${{ steps.get-version.outputs.version }}-${{ runner.os }}.tar.gz
        path: ${{ inputs.path }}/output.tar.gz
        retention-days: 1